name: PR analysis (Branch)

on: 
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  eslint:
    runs-on: ubuntu-latest
    name: runner / eslint
    permissions:
      contents: read
      pull-requests: write 
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ github.token }}
          eslint_flags: 'src/'

  annotate-pr:
    runs-on: ubuntu-latest
    name: Run tests on pull request
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      
      - run: yarn install

      - name: Building
        run: yarn build

      - name: Package
        run: yarn package

      - name: Annotate PR
        uses: ./