name: PR analysis

on: 
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  annotate-pr:
    runs-on: ubuntu-latest
    name: Run tests on pull request
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Annotate PR
        uses: ./